import { InsertCategorySchema } from "./validation"

export const categories: InsertCategorySchema[] = [
  { name: "Pizzas" },
  { name: "Snacks" },
  { name: "Coffee" },
  { name: "Drinks" },
  { name: "Desserts" },
  { name: "Sauces" },
  { name: "Burgers" },
  { name: "Wraps" },
  { name: "Pasta" },
  { name: "Salads" },
  { name: "Soups" },
  { name: "Smoothies" },
  { name: "Juices" },
  { name: "Sandwiches" },
  { name: "Fries" },
  { name: "Tacos" },
  { name: "Burritos" },
  { name: "Wings" },
  { name: "Breakfast" },
  { name: "Hot Dogs" },
  { name: "Grilled" },
  { name: "Steaks" },
  { name: "Seafood" },
  { name: "Sushi" },
  { name: "Appetizers" },
  { name: "Entrees" },
  { name: "Kids Meals" },
  { name: "Specials" },
  { name: "Frozen" },
  { name: "Dairy" },
  { name: "Bakery" },
  { name: "Vegan" },
  { name: "Vegetarian" },
  { name: "Gluten-Free" },
  { name: "Deli" },
  { name: "Grains" },
  { name: "Ice Cream" },
  { name: "Frozen Yogurt" },
  { name: "Confectionery" },
  { name: "Candies" },
  { name: "Chocolates" },
  { name: "Nuts" },
  { name: "Dried Fruits" },
  { name: "Cereals" },
  { name: "Energy Bars" },
  { name: "Teas" },
  { name: "Herbal Drinks" },
  { name: "Protein Shakes" },
  { name: "Mocktails" },
  { name: "Cocktails" },
  { name: "Spices" },
  { name: "Herbs" },
  { name: "Pickles" },
  { name: "Condiments" },
  { name: "Seasonings" },
  { name: "Toppings" },
  { name: "Side Dishes" },
  { name: "Hot Beverages" },
  { name: "Cold Beverages" },
  { name: "Milkshakes" },
  { name: "Biscuits" },
  { name: "Gourmet" },
  { name: "International" },
  { name: "Ethnic Foods" },
  { name: "Prepared Meals" },
  { name: "Organic" },
]

// export const categories: InsertCategorySchema[] = [
//   { name: "Pizzas" },
//   { name: "Snakes" },
//   { name: "Coffee" },
//   { name: "Drinks" },
//   { name: "Desserts" },
//   { name: "Sauces" },
// ]
